# Generated by Django 5.0.1 on 2024-01-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board_games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nickname',
        ),
        migrations.AddConstraint(
            model_name='gamescollection',
            constraint=models.UniqueConstraint(fields=('game', 'user'), name='unique_collection'),
        ),
    ]
