# Generated by Django 5.0.1 on 2024-01-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board_games', '0003_alter_users_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='Board_games.roles'),
        ),
    ]
